### ISSUE TITLE
Switch source of count for Thuringia

### ISSUE THREAD

**Issue by bueltge** [micb25/corona-jena#1]
Maybe you should use the site from the R.Koch institute to get the values for Thuringia - https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4
Maybe more solid and easier to parse them.

best regards.

**Comment by micb25** [comment]
Thanks for this suggestion! I have added the RKI numbers for Thuringia and the corresponding figures. I will also add a crawler to obtain these numbers on a daily basis soon.

Concerning the RKI numbers: the RKI changed the way of counting the case numbers in the past. As a consequence, the projected numbers based on an exponential trend show large error margins at the moment.

Unfortunately, there is also some delay connected with these numbers, which can be very crucial once the daily infection rate goes further up. However, this was the initial idea of this project: obtaining the case numbers on a local level to have a more accurate picture as well as plotting the data as a function of time. I think this is more useful and easier to understand for people than large tables with a lot of numbers. 

Lastly, I am very thankful to cities like Jena and Weimar, because they share these numbers on their websites.
